apiVersion: v1 
kind: Service
metadata:
  name: db
  namespace: vote 
  labels:
    name: postgres-service
    app: demo-voting-app
spec:
  selector:
    name: postgres-pod
    app: demo-voting-app 
  ports:
  - port: 5432
    targetPort: 5432