apiVersion: v1 
kind: Service
metadata:
  name: result-service
  namespace: vote
  labels:
    name: result-app-service
    app: demo-voting-app
spec:
  selector:
    name: result-app-pod
    app: demo-voting-app 
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30005