apiVersion: v1 
kind: Service
metadata:
  name: vot-service
  namespace: vote
  labels:
    name: voting-app-service
    app: demo-voting-app
spec:
  selector:
    name: voting-app-pod
    app: demo-voting-app 
  type: NodePort 
  ports:
  - port: 5000
    targetPort: 80
    nodePort: 31000
